config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "users#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  post "/register", to: "users#create"

  resources :users, only: [:index, :update]
  resources :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :receiver, class_name: "User"
    
    validates :amount, numericality: {greater_than: 0}
    validates :sender_id, presence: true
    validates :receiver_id, presence: true
    validates :approved, inclusion: {in: [ true, false ]}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :sender_transactions, foreign_key: "sender_id", class_name: "Transaction"
    has_many :receiver_transactions, foreign_key: "receiver_id", class_name: "Transaction"

    validates :username, presence: { message: "You must enter a username" }, uniqueness: { message: "Username is already taken" }, length: {maximum: 10, message: "Must be less than 10 characters"}
    validates :balance, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    private
    def require_login
        redirect_to login_path unless User.find_by_username(session[:username])
    end

    def already_logged_in        
        redirect_to root_path if User.find_by_username(session[:username])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    before_action :already_logged_in, only: [:new, :create]
    
    def new
    end

    def create
        @user = User.find_by_username(params[:username])

        if @user
            session[:username] = @user.username
            redirect_to root_path
        else
            if params[:username] == ""
                flash.now[:error] = "You must enter a username"
            else
                flash.now[:error] = "User doesn't exist"
            end
            render :new
        end
    end

    def destroy
        session[:username] = nil
        redirect_to login_path
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

    def index
        @current_user = User.find_by_username(session[:username])
        @approved_transactions = Transaction.all.where(approved: true, sender_id: @current_user.id).or(Transaction.all.where(approved: true, receiver_id: @current_user.id))
        @unapproved_transactions = Transaction.all.where(approved: false, sender_id: @current_user.id).or(Transaction.all.where(approved: false, receiver_id: @current_user.id))
    end

    def new
        @transaction = Transaction.new
    end

    def create 
        @transaction = Transaction.new
        
        if params[:transaction][:target_username] == session[:username]
            flash.now[:error] = "Can't transfer to yourself"
            render :new
            return
        elsif params[:transaction][:target_username] == ""
            flash.now[:error] = "You must enter a username"
            render :new
            return
        elsif params[:transaction] == "0"
            flash.now[:error] = "Cannot send 0 dollars"
            render :new
            return
        elsif params[:commit] == "Send" && User.find_by_username(session[:username]).balance < params[:transaction][:amount].to_f
            flash.now[:error] = "You don't have enough funds"
            render :new
            return
        end

        if params[:commit] == "Send"
            @sender = User.find_by_username(session[:username])
            @receiver = User.find_by_username(params[:transaction][:target_username]) if User.find_by_username(params[:transaction][:target_username])
            @approved = true
        elsif params[:commit] == "Request"
            @sender = User.find_by_username(params[:transaction][:target_username]) if User.find_by_username(params[:transaction][:target_username])
            @receiver = User.find_by_username(session[:username])
            @approved = false
        end
        
        @transaction.sender_id = @sender ? @sender.id : -1
        @transaction.receiver_id = @receiver ? @receiver.id : -1
        @transaction.amount = params[:transaction][:amount]
        @transaction.approved = @approved

        if @transaction.save
            if @transaction.approved
                update_balances(@sender, @receiver, @transaction.amount)
            end
            redirect_to root_path
        else
            flash.now[:error] = @transaction.errors.full_messages[0]
            render :new
        end
    end

    def update
        @transaction = Transaction.find(params[:id])

        if @transaction.amount <= User.find(@transaction.sender_id).balance
            @transaction.update(approved: true)        
            update_balances(User.find(@transaction.sender_id), User.find(@transaction.receiver_id), @transaction.amount)
            redirect_to root_path
        else
            @current_user = User.find_by_username(session[:username])
            @approved_transactions = Transaction.all.where(approved: true, sender_id: @current_user.id).or(Transaction.all.where(approved: true, receiver_id: @current_user.id))
            @unapproved_transactions = Transaction.all.where(approved: false, sender_id: @current_user.id).or(Transaction.all.where(approved: false, receiver_id: @current_user.id))
            flash.now[:error] = "You don't have enough funds"
            render :index
        end
    end

    private

    def update_balances(sender, receiver, amount)
        sender.update(balance: sender.balance - @transaction.amount)
        receiver.update(balance: receiver.balance + @transaction.amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create, :update]
    before_action :already_logged_in, only: [:new, :create]
    
    def show
        @current_user = User.find_by_username(session[:username])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new({username: params[:username], balance: 0})

        if @user.save
            flash[:success] = "Welcome to Coin App!"
            session[:username] = @user.username
            redirect_to root_path
        else
            flash.now[:error] = @user.errors[:username][0]
            render :new
        end
    end

    def update
        @current_user = User.find(params[:id])
        @current_user.update(balance: @current_user.balance + 10)                
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<% flash.each do |name, message| %>
    <a href="/transactions">
        <div class=<%= name %>>
            <%= message %>
        </div>
    </a>    
<% end %>

<div class="transaction_history_container">
    <div class="pending_body">

        <div class="pending_label">Pending</div>

        <% @unapproved_transactions.each do |transaction| %>
            <div class="transaction_row">
                <div>
                    <% if transaction.sender.username == @current_user.username %>
                        <%= transaction.receiver.username %>
                    <% else %>
                        <%= transaction.sender.username %>
                    <% end %>                    
                </div>
                <div class="row_right">
                    <% if transaction.sender.username == @current_user.username %>
                        -<%= number_to_currency(transaction.amount) %>
                    <% else %>
                       <%= number_to_currency(transaction.amount) %>
                    <% end %>

                    <% if transaction.sender.username == @current_user.username %>
                        <%= link_to "Accept", transaction_path(:id => transaction.id), method: :patch, class:"approve" %>
                    <% else %>
                        <div class="placeholder"></div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="past_body">
        <div class="past_label">Past</div>
        <% @approved_transactions.each do |transaction| %>
            <div class="transaction_row">
                <div>
                    <% if transaction.sender.username == @current_user.username %>
                        <%= transaction.receiver.username %>
                    <% else %>
                        <%= transaction.sender.username %>
                    <% end %>
                </div>
                <div>
                    <div class="row_right">
                        <% if transaction.sender.username == @current_user.username %>
                            -<%= number_to_currency(transaction.amount) %>             
                        <% else %>
                            <%= number_to_currency(transaction.amount) %>                        
                        <% end %>                    
                        <div class="placeholder"></div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="side_nav">
    <%= link_to root_path do %>
        <%= image_tag "user.png", class:"nav_top"%>
    <% end %>
    
    <%= link_to transactions_path do %>
        <%= image_tag "time_filled.png", class:"nav_top"%>
    <% end %>
    
    <%= link_to new_transaction_path do %>
        <%= image_tag "coin.png", class:"nav_bottom" %>
    <% end %>
</div>

app/views/transactions/new.html.erb
<% flash.each do |name, message| %>
    <a href="/transactions/new">
        <div class=<%= name %>>
            <%= message %>
        </div>
    </a>    
<% end %>   



<%= form_with model: @transaction do |form| %>
    <div class="new_transaction_container">

        <%= form.text_field :target_username, placeholder:"username", autocomplete:"off" %>

        <%= form.hidden_field :amount %>

        <div class="amount_display">$0</div>

        <div class="number_input_container">
            <div class="amount_input number_input">1</div>
            <div class="amount_input number_input">2</div>
            <div class="amount_input number_input">3</div>
            <div class="amount_input number_input">4</div>
            <div class="amount_input number_input">5</div>
            <div class="amount_input number_input">6</div>
            <div class="amount_input number_input">7</div>
            <div class="amount_input number_input">8</div>
            <div class="amount_input number_input">9</div>
            <div class="amount_input decimal_point">.</div>            
            <div class="amount_input number_input">0</div>
            <div class="amount_input backspace"><</div>         
        </div>

        <div class="transaction_buttons">
            <%= form.submit 'Send' %>
            <%= form.submit 'Request' %>
        </div>
    </div>
<% end %>


<div class="side_nav">
    <%= link_to root_path do %>
        <%= image_tag "user.png", class:"nav_top"%>
    <% end %>    

    <%= link_to transactions_path do %>
        <%= image_tag "time.png", class:"nav_top" %>
    <% end %>

    <%= link_to new_transaction_path do %>
        <%= image_tag "coin_filled.png", class:"nav_bottom" %>
    <% end %>
</div>


<%= javascript_pack_tag 'new_transaction' %>

app/views/users/new.html.erb
<% flash.each do |name, message| %>
    <div class=<%= name %>>
        <%= message %>
    </div>
<% end %>   

<div class="root_container">

    <div class="root_body">
        <%= image_tag "coin.png", class:"logo" %>

        <%= form_with url: "/register", class: "root_form_area" do |form| %>
            <%= form.text_field :username, class:"username_input", autocomplete:"off" %>

            <%= form.submit "Create user", class:"login_register" %>
        <% end %>        
    </div>
    
    <%= link_to "Log In", login_path, class:"switch_login_register" %>

</div>

<div class="help_hover">
    <%= image_tag "help.png", class:"help" %>
    <span class="tooltiptext">This is a toy clone of Cash App. Use two different browsers and accounts for the full experience.</span>
</div>

<%= javascript_pack_tag 'new_user' %>

app/views/users/show.html.erb
<% flash.each do |name, message| %>
    <a href="">
        <div class=<%= name %>>
            <%= message %>
        </div>
    </a>    
<% end %>

<div class="user_container">

    <div class="user_body">
        <div class="username">
            <%= @current_user.username %>
        </div>

        <div class="current_balance">
            <%= number_to_currency(@current_user.balance) %>
        </div>

        <div class="current_balance_label">Balance</div>

        <%= link_to "Hax: Add $10", user_path(@current_user), method: :patch, class:"hax" %>
    </div>

    <%= link_to "Logout", logout_path, :method => "delete", class:"logout" %>

</div>

<div class="side_nav">
    <%= link_to root_path do %>
        <%= image_tag "user_filled.png", class:"nav_top"%>
    <% end %>

    <%= link_to transactions_path do %>
        <%= image_tag "time.png", class:"nav_top"%>
    <% end %>

    <%= link_to new_transaction_path do %>
        <%= image_tag "coin.png", class:"nav_bottom" %>
    <% end %>
</div>